project_id = "sinflvoxbphblalcsaba"

[functions.document-lookup]
verify_jwt = false

[functions.sponsor-lookup]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.document-check]
verify_jwt = false

[functions.username-check]
verify_jwt = false

[functions.send-recovery-email]
verify_jwt = false

[functions.check-incomplete-registrations]
verify_jwt = false

[functions.continue-registration]
verify_jwt = false
